# Generated by Django 2.2.12 on 2020-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('filingtype', models.CharField(max_length=255)),
                ('filingdate', models.CharField(max_length=255)),
                ('filingpath', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.UniqueConstraint(fields=('filingpath', 'filingdate'), name='path_date constraint'),
        ),
    ]
