# Generated by Django 2.2.12 on 2020-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgarapp', '0002_auto_20200527_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('classTitle', models.CharField(max_length=255)),
                ('CUSIP', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('share_prn_amount', models.CharField(max_length=255)),
                ('share_prn_type', models.CharField(max_length=255)),
                ('put_call', models.CharField(max_length=255)),
                ('investment_discretion', models.CharField(max_length=255)),
                ('other_manager', models.CharField(max_length=255)),
                ('sole_voting_authority', models.CharField(max_length=255)),
                ('shared_voting_authority', models.CharField(max_length=255)),
                ('none_voting_authority', models.CharField(max_length=255)),
            ],
        ),
    ]
