# Generated by Django 2.2.12 on 2020-07-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgarapp', '0003_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
    ]
